[
  (let_statement)
  (unlet_statement)
  (const_statement)
  (set_statement)
  (setlocal_statement)
  (return_statement)
  (normal_statement)
  (lua_statement)
  (range_statement)
  (ruby_statement)
  (python_statement)
  (perl_statement)
  (call_statement)
  (execute_statement)
  (echo_statement)
  (echon_statement)
  (echohl_statement)
  (echomsg_statement)
  (echoerr_statement)
  (try_statement)
  (throw_statement)
  (autocmd_statement)
  (silent_statement)
  (vertical_statement)
  (belowright_statement)
  (aboveleft_statement)
  (topleft_statement)
  (botright_statement)
  (register_statement)
  (map_statement)
  (augroup_statement)
  (bang_filter_statement)
  (highlight_statement)
  (syntax_statement)
  (setfiletype_statement)
  (options_statement)
  (startinsert_statement)
  (stopinsert_statement)
  (scriptencoding_statement)
  (source_statement)
  (global_statement)
  (colorscheme_statement)
  (command_statement)
  (comclear_statement)
  (delcommand_statement)
  (filetype_statement)
  (runtime_statement)
  (wincmd_statement)
  (sign_statement)
  (break_statement)
  (continue_statement)
  (cnext_statement)
  (cprevious_statement)
  (unknown_builtin_statement)
  (edit_statement)
  (enew_statement)
  (find_statement)
  (ex_statement)
  (visual_statement)
  (view_statement)
  (eval_statement)
  (substitute_statement)
  (user_command)
] @output_statement

(function_definition
  (body) @output_statement.inside) @output_statement

(for_loop
  (body) @output_statement.inside) @output_statement

(if_statement
  (body) @output_statement.inside) @output_statement

(while_loop
  (body) @output_statement.inside) @output_statement
