name: Run tests

on:
  pull_request:
    paths: ["lua/**", "tests/**", "plugin/**", "queries/**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build:
    name: Run tests
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        neovim_version: ["v0.12.1", "nightly"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: tree-sitter/setup-action/cli@v2
      - name: Setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}
      - name: Setup deps
        run: make deps
      - name: Run tests
        run: make test
